// <auto-generated />
namespace Twilio.OwlFinance.Infrastructure.DataAccess.Configuration.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChatMessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChatMessages));
        
        string IMigrationMetadata.Id
        {
            get { return "201605061450022_ChatMessages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
